#!/usr/bin/env python3
"""Generates src/KaartdataTabel.hxx from the truckermudgeon/maps parser output.

Usage:  python maak_tabel.py <dir with europe-cities.json, europe-pois.json, europe-version.txt>

The parser (github.com/truckermudgeon/maps, GPL-3.0) reads the installed game and
writes JSON; run it once per game/map-DLC version:
    npx tsx packages\\clis\\parser\\index.ts -i "<ETS2 folder>" -o <out dir>
Only tokens and coordinates are copied into the table -- no game assets."""
import json, os, sys
d = sys.argv[1]
c = json.load(open(os.path.join(d, 'europe-cities.json')))
p = json.load(open(os.path.join(d, 'europe-pois.json')))
versie = open(os.path.join(d, 'europe-version.txt')).read().strip()
steden = sorted({(x['token'], x['countryToken'], round(x['x'], 1), round(x['y'], 1)) for x in c})
garages = sorted({(round(x['x'], 1), round(x['y'], 1)) for x in p if x.get('icon') == 'garage_large_ico'})
# Every large garage carries its own pump as a gas_ico POI, normally 20 m from
# the garage point; one variant (garage_expensive_sc, Ljubljana) has it at 39 m,
# and public stations can stand 50-66 m from a garage (Dortmund, Nantes,
# Jyvaskyla). So: per garage, the NEAREST pump within 70 m is its own pump --
# exactly one -- and every other pump is public. Measured on 1.60.1.7.
import math
alle_pompen = [(x['x'], x['y']) for x in p if x.get('icon') == 'gas_ico']
garage_pompen = set()
for gx, gz in garages:
    if not alle_pompen: break
    px, pz = min(alle_pompen, key=lambda q: math.hypot(q[0] - gx, q[1] - gz))
    if math.hypot(px - gx, pz - gz) < 70.0:
        garage_pompen.add((round(px, 1), round(pz, 1)))
pompen = sorted({(round(x, 1), round(z, 1), (round(x, 1), round(z, 1)) in garage_pompen) for x, z in alle_pompen})
def f(v):
    return f'{float(v):.1f}f'
def arr(naam, rows, fmt):
    return f"    static const {naam}[] = {{\n" + "\n".join("        " + fmt(r) + "," for r in rows) + "\n    };\n"
h = f'''#pragma once
// ---------------------------------------------------------------------------
// KaartdataTabel.hxx -- GENERATED by tools/kaartdata/maak_tabel.py, do not
// edit by hand.
//
// City centres, large-garage sites and fuel stations of the ETS2 map, with
// their world coordinates (X and Z in game metres; height dropped). The
// coordinate frame is the same one the TruckersMP SDK reports vehicle
// placements in, so a live position can be matched directly.
//
// Source: the game's own map data of version {versie}, parsed once with the
// open-source truckermudgeon/maps parser (GPL-3.0). Only coordinates and
// tokens are kept here -- no game assets.
//
// Why embedded: the plugin must never depend on a file that may be missing.
// ---------------------------------------------------------------------------

namespace Ritten::Kaart
{{
    constexpr const char *KAART_VERSIE = "{versie}";

    struct Stad {{ const char *token; const char *land; float x; float z; }};
    struct Punt {{ float x; float z; }};
    struct Pomp {{ float x; float z; bool garage; }};

{arr("Stad STEDEN", steden, lambda r: f'{{ "{r[0]}", "{r[1]}", {f(r[2])}, {f(r[3])} }}')}
{arr("Punt GARAGES", garages, lambda r: f'{{ {f(r[0])}, {f(r[1])} }}')}
{arr("Pomp POMPEN", pompen, lambda r: f'{{ {f(r[0])}, {f(r[1])}, {"true" if r[2] else "false"} }}')}
    constexpr int AANTAL_STEDEN = {len(steden)};
    constexpr int AANTAL_GARAGES = {len(garages)};
    constexpr int AANTAL_POMPEN = {len(pompen)};
}}
'''
uit = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'src', 'KaartdataTabel.hxx')
open(uit, 'w', encoding='utf-8').write(h)
# Same data as JSON, for the optional download at startup (data/kaartdata.json in the repo).
jpad = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'data', 'kaartdata.json')
os.makedirs(os.path.dirname(jpad), exist_ok=True)
json.dump({'versie': versie,
           'steden': [[t, l, x, y] for t, l, x, y in steden],
           'garages': [[x, y] for x, y in garages],
           'pompen': [[x, y, int(g)] for x, y, g in pompen]},
          open(jpad, 'w', encoding='utf-8'), separators=(',', ':'))
print(f"also wrote {jpad}")
print(f"{len(steden)} cities, {len(garages)} garages, {len(pompen)} fuel stations ({sum(1 for r in pompen if r[2])} at garages), version {versie} -> {uit}")
